### ISSUE TITLE
не нужно пеердавать тайтл. просто используй разные темплейты

### ISSUE THREAD

**Issue by paladinbbk** [PHPHillelYuriev/Symfony-test#4]
https://github.com/PHPHillelYuriev/Symfony-test/blob/f5be2f226b9a8e59b65ca8107144f9d328cf4fa9/src/Controller/MainController.php#L28

**Comment by PHPHillelYuriev** [comment]
Удалил тайтлы перенеся их в соответсвующие шаблоны
